version: 0.0
os: linux
files:
- source: ./public_html
  destination: /var/www/html
  overwrite: yes
hooks:
  BeforeInstall:
  - location: stop_server
  AfterInstall:
  - location: start_server
    timeout: 300
    runas: root
  ApplicationStart:
  - location: start_server
    timeout: 300
    runas: root
  ValidateService:
  - location: status_server
    timeout: 300
    runas: root

